#!/usr/bin/env bash

# Tmux Sessionizer (Inspired by ThePrimeagen)
# Fuzzy find a directory and open it in a new tmux session
ts() {
    local selected
    if [[ $# -eq 1 ]]; then
        selected=$1
    else
        selected=$(find ~/Work ~/Desktop ~/Documents ~/dotfiles -mindepth 1 -maxdepth 2 -type d | fzf)
    fi

    if [[ -z $selected ]]; then
        return 0
    fi

    local selected_name=$(basename "$selected" | tr . _)
    local tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s $selected_name -c $selected
        return 0
    fi

    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
    fi

    tmux switch-client -t $selected_name
}

# Interactive cheat.sh lookup
cheat() {
    local query
    if [[ $# -eq 0 ]]; then
        echo "Usage: cheat <command>"
        return 1
    fi
    curl -s "cheat.sh/$1" | bat --style=plain --paging=always
}

# TTY-friendly system monitor
sys() {
    btop --preset 0
}
